### ISSUE TITLE
Closed lines appear as empty

### ISSUE THREAD

**Issue by cypressious** [cypressious/KitMensaAndroid#3]
![grafik](https://user-images.githubusercontent.com/1191816/74109023-1cd77200-4b80-11ea-97f8-66e306fd7301.png)

![grafik](https://user-images.githubusercontent.com/1191816/74109026-1fd26280-4b80-11ea-9041-a7233f5ad62c.png)

@SeineEloquenz do you have interest in working on this?

**Comment by SeineEloquenz** [comment]
I can look into it, yes
